# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: obstacleSel.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='obstacleSel.proto',
  package='pb_obstacle_sel',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11obstacleSel.proto\x12\x0fpb_obstacle_sel\"I\n\x07LogFile\x12\x17\n\x0f\x66rame_total_num\x18\x01 \x01(\x05\x12%\n\x05\x66rame\x18\x02 \x03(\x0b\x32\x16.pb_obstacle_sel.Frame\"t\n\x05\x46rame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12#\n\x04path\x18\x02 \x01(\x0b\x32\x15.pb_obstacle_sel.Path\x12\x34\n\robstacle_list\x18\x03 \x01(\x0b\x32\x1d.pb_obstacle_sel.ObstacleList\"^\n\x08PathNode\x12\r\n\x05\x63\x61r_x\x18\x01 \x01(\x02\x12\r\n\x05\x63\x61r_y\x18\x02 \x01(\x02\x12\x0e\n\x06\x66lat_x\x18\x03 \x01(\x02\x12\x0e\n\x06\x66lat_y\x18\x04 \x01(\x02\x12\t\n\x01s\x18\x05 \x01(\x02\x12\t\n\x01\x64\x18\x06 \x01(\x02\"E\n\x04Path\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12,\n\tpath_node\x18\x02 \x03(\x0b\x32\x19.pb_obstacle_sel.PathNode\"\x86\x01\n\x08Obstacle\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\r\n\x05pos_x\x18\x03 \x01(\x02\x12\r\n\x05pos_y\x18\x04 \x01(\x02\x12\r\n\x05pos_s\x18\x05 \x01(\x02\x12\r\n\x05pos_d\x18\x06 \x01(\x02\x12\x11\n\trel_spd_x\x18\x07 \x01(\x02\x12\x11\n\trel_spd_y\x18\x08 \x01(\x02\"H\n\x0cObstacleList\x12\x0b\n\x03num\x18\x01 \x01(\x05\x12+\n\x08obstacle\x18\x02 \x03(\x0b\x32\x19.pb_obstacle_sel.Obstacleb\x06proto3'
)




_LOGFILE = _descriptor.Descriptor(
  name='LogFile',
  full_name='pb_obstacle_sel.LogFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_total_num', full_name='pb_obstacle_sel.LogFile.frame_total_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame', full_name='pb_obstacle_sel.LogFile.frame', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=111,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='pb_obstacle_sel.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='pb_obstacle_sel.Frame.frame_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='pb_obstacle_sel.Frame.path', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obstacle_list', full_name='pb_obstacle_sel.Frame.obstacle_list', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=229,
)


_PATHNODE = _descriptor.Descriptor(
  name='PathNode',
  full_name='pb_obstacle_sel.PathNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='car_x', full_name='pb_obstacle_sel.PathNode.car_x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='car_y', full_name='pb_obstacle_sel.PathNode.car_y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flat_x', full_name='pb_obstacle_sel.PathNode.flat_x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flat_y', full_name='pb_obstacle_sel.PathNode.flat_y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='s', full_name='pb_obstacle_sel.PathNode.s', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d', full_name='pb_obstacle_sel.PathNode.d', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=325,
)


_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='pb_obstacle_sel.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='pb_obstacle_sel.Path.node_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path_node', full_name='pb_obstacle_sel.Path.path_node', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=396,
)


_OBSTACLE = _descriptor.Descriptor(
  name='Obstacle',
  full_name='pb_obstacle_sel.Obstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb_obstacle_sel.Obstacle.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='pb_obstacle_sel.Obstacle.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_x', full_name='pb_obstacle_sel.Obstacle.pos_x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_y', full_name='pb_obstacle_sel.Obstacle.pos_y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_s', full_name='pb_obstacle_sel.Obstacle.pos_s', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_d', full_name='pb_obstacle_sel.Obstacle.pos_d', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rel_spd_x', full_name='pb_obstacle_sel.Obstacle.rel_spd_x', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rel_spd_y', full_name='pb_obstacle_sel.Obstacle.rel_spd_y', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=533,
)


_OBSTACLELIST = _descriptor.Descriptor(
  name='ObstacleList',
  full_name='pb_obstacle_sel.ObstacleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='pb_obstacle_sel.ObstacleList.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obstacle', full_name='pb_obstacle_sel.ObstacleList.obstacle', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=607,
)

_LOGFILE.fields_by_name['frame'].message_type = _FRAME
_FRAME.fields_by_name['path'].message_type = _PATH
_FRAME.fields_by_name['obstacle_list'].message_type = _OBSTACLELIST
_PATH.fields_by_name['path_node'].message_type = _PATHNODE
_OBSTACLELIST.fields_by_name['obstacle'].message_type = _OBSTACLE
DESCRIPTOR.message_types_by_name['LogFile'] = _LOGFILE
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['PathNode'] = _PATHNODE
DESCRIPTOR.message_types_by_name['Path'] = _PATH
DESCRIPTOR.message_types_by_name['Obstacle'] = _OBSTACLE
DESCRIPTOR.message_types_by_name['ObstacleList'] = _OBSTACLELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogFile = _reflection.GeneratedProtocolMessageType('LogFile', (_message.Message,), {
  'DESCRIPTOR' : _LOGFILE,
  '__module__' : 'obstacleSel_pb2'
  # @@protoc_insertion_point(class_scope:pb_obstacle_sel.LogFile)
  })
_sym_db.RegisterMessage(LogFile)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'obstacleSel_pb2'
  # @@protoc_insertion_point(class_scope:pb_obstacle_sel.Frame)
  })
_sym_db.RegisterMessage(Frame)

PathNode = _reflection.GeneratedProtocolMessageType('PathNode', (_message.Message,), {
  'DESCRIPTOR' : _PATHNODE,
  '__module__' : 'obstacleSel_pb2'
  # @@protoc_insertion_point(class_scope:pb_obstacle_sel.PathNode)
  })
_sym_db.RegisterMessage(PathNode)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), {
  'DESCRIPTOR' : _PATH,
  '__module__' : 'obstacleSel_pb2'
  # @@protoc_insertion_point(class_scope:pb_obstacle_sel.Path)
  })
_sym_db.RegisterMessage(Path)

Obstacle = _reflection.GeneratedProtocolMessageType('Obstacle', (_message.Message,), {
  'DESCRIPTOR' : _OBSTACLE,
  '__module__' : 'obstacleSel_pb2'
  # @@protoc_insertion_point(class_scope:pb_obstacle_sel.Obstacle)
  })
_sym_db.RegisterMessage(Obstacle)

ObstacleList = _reflection.GeneratedProtocolMessageType('ObstacleList', (_message.Message,), {
  'DESCRIPTOR' : _OBSTACLELIST,
  '__module__' : 'obstacleSel_pb2'
  # @@protoc_insertion_point(class_scope:pb_obstacle_sel.ObstacleList)
  })
_sym_db.RegisterMessage(ObstacleList)


# @@protoc_insertion_point(module_scope)
